/**
 * HTML Exporter - Generates HTML report with annotated screenshots
 */
export async function generateHtmlExport(data) {
    const startTime = data.steps[0]?.capturedAt
        ? new Date(data.steps[0].capturedAt).toLocaleTimeString()
        : "Unknown";
    const duration = data.steps.length > 0
        ? formatDuration(data.steps[data.steps.length - 1].capturedAt - data.steps[0].capturedAt)
        : "0:00";
    const stepsHtml = data.steps
        .map((step, index) => {
        const imageUrl = step.annotatedImageDataUrl || "#";
        return `
        <div class="step-card">
          <div class="step-header">
            <h3>Step ${index + 1}</h3>
            <p class="step-meta">${step.trigger} • ${step.image.width}×${step.image.height}</p>
          </div>
          <img src="${imageUrl}" alt="Step ${index + 1}" class="step-image" />
          ${step.description
            ? `<p class="step-description">${escapeHtml(step.description)}</p>`
            : ""}
        </div>
      `;
    })
        .join("");
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>PSRWeb Recording - Export</title>
  <style>
    :root {
      --bg: oklch(99% 0.002 240);
      --surface: oklch(100% 0 0);
      --fg: oklch(18% 0.012 250);
      --muted: oklch(54% 0.012 250);
      --border: oklch(92% 0.005 250);
      --accent: oklch(58% 0.18 255);
    }
    
    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }
    
    html {
      font-size: 14px;
    }
    
    body {
      background: var(--bg);
      color: var(--fg);
      font-family: -apple-system, BlinkMacSystemFont, 'SF Pro Display', system-ui, sans-serif;
      line-height: 1.6;
      padding: 20px;
    }
    
    .container {
      max-width: 900px;
      margin: 0 auto;
    }
    
    header {
      margin-bottom: 32px;
      padding: 20px;
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 8px;
    }
    
    h1 {
      font-size: 24px;
      font-weight: 600;
      margin-bottom: 16px;
    }
    
    .header-stats {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
      gap: 16px;
      font-size: 13px;
    }
    
    .stat {
      display: flex;
      flex-direction: column;
    }
    
    .stat-label {
      color: var(--muted);
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      margin-bottom: 4px;
    }
    
    .stat-value {
      font-size: 16px;
      font-weight: 600;
      color: var(--fg);
    }
    
    .steps {
      display: flex;
      flex-direction: column;
      gap: 16px;
    }
    
    .step-card {
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 8px;
      overflow: hidden;
    }
    
    .step-header {
      padding: 12px 16px;
      border-bottom: 1px solid var(--border);
      background: var(--bg);
    }
    
    .step-header h3 {
      font-size: 14px;
      font-weight: 600;
      margin-bottom: 4px;
    }
    
    .step-meta {
      font-size: 12px;
      color: var(--muted);
    }
    
    .step-image {
      width: 100%;
      display: block;
      aspect-ratio: 16 / 9;
      object-fit: cover;
    }
    
    .step-description {
      padding: 12px 16px;
      font-size: 13px;
      color: var(--fg);
      line-height: 1.5;
      border-top: 1px solid var(--border);
    }
    
    footer {
      margin-top: 32px;
      padding: 16px;
      text-align: center;
      font-size: 12px;
      color: var(--muted);
      border-top: 1px solid var(--border);
    }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>PSRWeb Recording</h1>
      <div class="header-stats">
        <div class="stat">
          <div class="stat-label">Started</div>
          <div class="stat-value">${startTime}</div>
        </div>
        <div class="stat">
          <div class="stat-label">Duration</div>
          <div class="stat-value">${duration}</div>
        </div>
        <div class="stat">
          <div class="stat-label">Steps</div>
          <div class="stat-value">${data.steps.length}</div>
        </div>
      </div>
    </header>
    
    <div class="steps">
      ${stepsHtml}
    </div>
    
    <footer>
      <p>Generated by PSRWeb • ${new Date().toLocaleString()}</p>
    </footer>
  </div>
</body>
</html>`;
    return new Blob([html], { type: "text/html" });
}
function formatDuration(ms) {
    const seconds = Math.floor(ms / 1000);
    const minutes = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${minutes}:${secs.toString().padStart(2, "0")}`;
}
function escapeHtml(text) {
    const map = {
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
        '"': "&quot;",
        "'": "&#039;",
    };
    return text.replace(/[&<>"']/g, (m) => map[m]);
}
